<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUU1IgwD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUU1IgwD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUU1IgwD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUU1IgwD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUU1IgwD\App_KernelDevDebugContainer([
    'container.build_hash' => 'UU1IgwD',
    'container.build_id' => 'f671cad9',
    'container.build_time' => 1640858155,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUU1IgwD');
