<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app_cliente_editarcliente' => [['id'], ['_controller' => 'App\\Controller\\ClienteController::editarCliente'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cliente/editar']], [], []],
    'app_cliente_borrarcliente' => [['id'], ['_controller' => 'App\\Controller\\ClienteController::borrarCliente'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cliente/borrar']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'listar_clientes' => [[], ['_controller' => 'App\\Controller\\ClienteController::listarClientes'], [], [['text', '/clientes']], [], []],
    'listar_clientes_servidor' => [[], ['_controller' => 'App\\Controller\\ClienteController::listarClientesServidor'], [], [['text', '/clientes/servidor']], [], []],
    'crear_cliente' => [[], ['_controller' => 'App\\Controller\\ClienteController::crearCliente'], [], [['text', '/cliente/crear']], [], []],
    'ver_cliente' => [['id'], ['_controller' => 'App\\Controller\\ClienteController::verCliente'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cliente']], [], []],
    'editar_cliente' => [['id'], ['_controller' => 'App\\Controller\\ClienteController::editarCliente'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cliente/editar']], [], []],
    'borrar_cliente' => [['id'], ['_controller' => 'App\\Controller\\ClienteController::borrarCliente'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cliente/borrar']], [], []],
];
